# Generated by Django 3.2.16 on 2023-01-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_data_migration_lesson"),
    ]

    operations = []
